### PR TITLE
i#1954: drltrace cmake references non-existent target

### LINKED ISSUE #1954: drltrace cmake references non-existent target
Looks like an error when moving this from the DR repo:

```
CMake Warning (dev) at drltrace/CMakeLists.txt:72 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "api_headers" of target "drltracelib" does not exist.
```

### PR DESCRIPTION
**Pull request by mxmssh**
fix cmake references of non-existent target for drltrace

Fixes #1954

### CODE REVIEW

**Comment by mxmssh** [comment]
Ready to merge.  AppVeyor failed so I can't squash and merge.

**Comment by egrimley** [comment]
You should probably mention an issue number for the AppVeyor failure, creating a new issue if necessary. If you're unsure whether it's a random failure you could perhaps push an empty commit to rerun the tests. (I get the impression the machines are less busy at this time of day so it's not very antisocial.)

**Comment by mxmssh** [comment]
This is #1938

**Comment by derekbruening** [comment]
If you could paste which test failed as well.  This is not #1938 -- the failure is:

```
free.shadow => ~~Dr.M~~ ASSERT FAILURE (thread 428): C:\projects\drmemory\drmemory\shadow.c:277: false (fail to create shadow memory mapping)
```

That is #1810.

**Pull request merged**
