### PR TITLE
i#2051: in frontend, check for execute not read of DR root dir

### LINKED ISSUE #2051: in frontend, check for execute not read of DR root dir
Today the Dr. Memory frontend does this check:
```
if (!file_is_readable(dr_root)) {
       fatal("invalid -dr_root %s", dr_root);
```

That's a directory, so it should really only check for +x, not +r.  That allows an installer to prevent list access and only allow traversal.

### PR DESCRIPTION
**Pull request by jwysowski**
Adds a new static function file_is_executable in frontend.c

Fixes #2051

### CODE REVIEW

**Comment by johnfxgalea** [comment]
Thank you @jwysowski for the patch!

LGTM!

**Review by johnfxgalea — APPROVED** [review]

**Comment by johnfxgalea** [comment]
Perhaps, @derekbruening could also take a look since he raised the issue and maybe has an alternative fix in mind?

**Review by derekbruening — APPROVED** [review]
LGTM.  Thank you for the patch!

**Comment by derekbruening** [comment]
Hmm, so why aren't the GA CI jobs running?  B/c this is a PR from a forked repo?  I thought the yaml had the right triggers for that and we even tested it on the DR repo.

**Comment by derekbruening** [comment]
> Hmm, so why aren't the GA CI jobs running? B/c this is a PR from a forked repo? I thought the yaml had the right triggers for that and we even tested it on the DR repo.

@abhinav92003 any ideas?  This repo has the same triggers as the DR repo workflows:
```
on:
  # Run on pushes to master and on pull request changes, including from a
  # forked repo with no "push" trigger, while avoiding duplicate triggers.
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
```

**Comment by abhinav92003** [comment]
> @abhinav92003 any ideas? This repo has the same triggers as the DR repo workflows:

DynamoRIO CI trigger for fork repo PRs can be seen in [dynamorio/PR#4634](https://github.com/DynamoRIO/dynamorio/pull/4634).

I tried doing it again in [dynamorio/PR#4771](https://github.com/DynamoRIO/dynamorio/pull/4771), and it still works. Though let me try syncing my forked repo to latest DR and re-try.

**Comment by derekbruening** [comment]
> > @abhinav92003 any ideas? This repo has the same triggers as the DR repo workflows:
> 
> DynamoRIO CI trigger for fork repo PRs can be seen in [dynamorio/PR#4634](https://github.com/DynamoRIO/dynamorio/pull/4634).
> 
> I tried doing it again in [dynamorio/PR#4771](https://github.com/DynamoRIO/dynamorio/pull/4771), and it still works. Though let me try syncing my forked repo to latest DR and re-try.

Huh, I wonder if there's sthg different in drmemory repo: though the .yml looks identical.  There aren't any other settings beyond the .yml right (and what branches are marked as required)?  I can do a test try for drmemory repo later today.

**Comment by derekbruening** [comment]
My fork test for drmemory repo is running the tests: #2390.
Could there be something where you and I have privileges in the original repo?
Have there been any dynamorio repo PR's from non-member forks since we put in GA CI -- maybe not, since khuey is a project member now.

**Comment by abhinav92003** [comment]
This seems relevant: https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054

Particularly,
```
The actions are in fact executed, but it happens against the _fork_, not against the base repo.

This does require that the forked repo also has actions enabled though.
```

**Comment by abhinav92003** [comment]
@jwysowski On the `Settings` page for your forked repository, see `Actions` on the left-hand side and please confirm whether actions are allowed.

**Comment by jwysowski** [comment]
Actions weren't enabled in my forked repository.

**Comment by abhinav92003** [comment]
> Actions weren't enabled in my forked repository.

After enabling them, please re-trigger CI on this branch. The way to do that would probably be either using the `Actions` tab on your forked repo, but I'm not sure if that'll reflect on this PR. If it doesn't work, then try submitting another commit to this branch.

**Comment by johnfxgalea** [comment]
@jwysowski Thanks for the path.

@abhinav92003 Thank you for investigating the issue regarding the CI.

**Pull request merged**
