### PR TITLE
i#2375: Fix faulty redzone test

### PR DESCRIPTION
**Pull request by johnfxgalea**
Fixes a bug in the test for faulty red zones. The bug led the test to potentially calculate app addresses with scratch registers not containing their original values.

Issue: #2375

### CODE REVIEW

**Comment by johnfxgalea** [comment]
@derekbruening Please take a look. Hopefully, the issue is now resolved. I can't be certain as I didn't find the root cause of #2375 as I cannot reproduce locally.

**Comment by johnfxgalea** [comment]
According to the CI, it seems like this PR didn't fix it. Marking the PR as draft, and will look again into it soon.

**Comment by johnfxgalea** [comment]
We need to fix the issue via DynamoRIO (which I will do next).

However, this PR is still useful in making the test more reliable and correct.

@derekbruening Appreciate if you can take a look! Thank you.

**Review by derekbruening — APPROVED** [review]

**Comment by johnfxgalea** [comment]
Created an issue for the new CI failure: https://github.com/DynamoRIO/drmemory/issues/2379

**Pull request merged**
